{% set name = "sithom" %}
{% set version = "0.0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: e256e0afa95184a548e346405248ab5abc948b35f490f239591787389b07d09c

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python


requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - cmocean
    - jupyterthemes
    - matplotlib-base
    - python >={{ python_min }}
    - seaborn
    - typeguard
    - uncertainties
    - xarray

test:
  requires:
    - python {{ python_min }}
  imports:
    - sithom

about:
  home: "https://github.com/sdat2/sithom"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "General utility scripts"
  doc_url: "https://sithom.readthedocs.io/en/latest/"
  dev_url: "https://github.com/sdat2/sithom"

extra:
  recipe-maintainers:
    - sdat2
